baseURL = "http://urovorozu.xyz/"
locale = "en-us"
title = "🐍"
theme = "nightfall"

[params]
user = "raz"
hostname = "urovorozu.xyz"
openLinksInNewTab = true
sitedescription = "The magic lives close to the edge"

[params.author]
name = "🐍"
email = "hi@urovorozu.xyz"

[[params.social]]
key = 0
name = "Bluesky (18+)"
url = "https://bsky.app/profile/did:plc:g6hmilvcmmkpx6gepruk5ekl"
icon = "fa-brands fa-bluesky"

[[params.social]]
key = 1
name = "X (18+)"
url = "https://x.com/_rz13"
icon = "fa-brands fa-x-twitter"

[[params.social]]
key = 2
name = "Signal"
url = "https://signal.me/#eu/SOuTeE9pIFzaHkK7JDzVROmbkxqSkETUHMUGiQDfE-HTATCNJOtG64mJ0LdeD-I6"
icon = "fa-brands fa-signal-messenger"

[[params.social]]
key = 3
name = "Email"
url = "mailto:hi@urovorozu.xyz"
icon = "fa-regular fa-envelope"

[menu]
  [[menu.header]]
    name = "about"
    url = "/about"
    
  [[menu.header]]
    name = "blog"
    url = "/blog"

  [[menu.header]]
    name = "wakfu"
    url = "/wakfu"